name: terraform-destroy
# Deploy manually
on: workflow_dispatch

env:
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID_REQUIRED }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY_REQUIRED }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  TF_LOG: ${{ vars.TF_LOG }}
  TF_VAR_AWS_KEYPAIR_NAME: ${{ vars.AWS_KEYPAIR_NAME }}
  TF_VAR_RDP_IP_ADDRESS: ${{ vars.RDP_IP_ADDRESS }}

jobs:
  Terraform-Destroy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3

    - name: Terraform Set Env
      id: set-env
      run: scripts/tf-backend.sh -e

    - name: Terraform Init
      id: init
      run: terraform init -backend-config="bucket=$S3_TF_STATE"

    - name: Terraform Destroy
      id: destroy
      run: terraform destroy -auto-approve

    - name: Terraform Backend
      id: backend
      run: scripts/tf-backend.sh -d
